format = 1

[[binding]]
address = "83:BBF3"
bridge = "Lufia2DecompBridge_BBF3"

[[binding]]
address = "83:D350"
bridge = "Lufia2DecompBridge_D350"

[[binding]]
address = "83:F9D4"
bridge = "Lufia2DecompBridge_F9D4"

[[binding]]
address = "83:FB12"
bridge = "Lufia2DecompBridge_FB12"

[[binding]]
address = "83:FB71"
bridge = "Lufia2DecompBridge_FB71"

[[binding]]
address = "83:C7F8"
bridge = "Lufia2DecompBridge_C7F8"

[[binding]]
address = "83:D508"
bridge = "Lufia2DecompBridge_D508"

[[binding]]
address = "83:C1B4"
bridge = "Lufia2DecompBridge_C1B4"

[[binding]]
address = "83:BB93"
bridge = "Lufia2DecompBridge_BB93"

[[binding]]
address = "83:81C6"
bridge = "Lufia2DecompBridge_81C6"

[[binding]]
address = "83:E03E"
bridge = "Lufia2DecompBridge_E03E"

[[binding]]
address = "83:9FA9"
bridge = "Lufia2DecompBridge_9FA9"

[[binding]]
address = "8E:BD77"
bridge = "Lufia2DecompBridge_BD77"
