#!/usr/bin/env python3
"""T14 AC1: static contract table for the Ancient Cave floor generator.

Reads the user's own supported ROM and walks `$83:9E31` (entry M1/X0) with
every reachable child, printing a Markdown contract table: entry M/X per call
site, exit outcomes, stack balance, DB/DP effects, the caller DB/DP each
routine depends on, MMIO, dynamic transfers and every candidate direct caller
elsewhere in the ROM. The output contains addresses and decoded operands
only; it never copies ROM data.

This is research evidence. Every contract still needs an original-ROM probe.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cfg65816 import (  # noqa: E402
    ENTRY, Analyzer, LoRom, describe_value, fmt, fmt_mx, parse_address,
    scan_ram_writers, scan_references)

SUPPORTED_SHA256 = (
    "7C34ECB16C10F551120ED7B86CFBC947042F479B52EE74BB3C40E92FDD192B3A")
ROM_SIZE = 0x280000

# $80:80E1 installs `MVN dst,src ; RTS` at $057D/$0580 during boot; callers
# patch the operand bytes $057E (destination) and $057F (source bank).
MVN_STUB = 0x057D
MVN_OPERANDS = {0x057E, 0x057F}


def mvn_stub_model(insn, state):
    known = dict(state.wram)
    dst, src = known.get(0x057E), known.get(0x057F)
    text = "MVN {},{} ; RTS".format(
        f"${dst:02X}" if dst is not None else "?",
        f"${src:02X}" if src is not None else "?")
    # MVN leaves DB = destination bank and A = $FFFF; widths and S unchanged.
    return state.with_(db=dst, a_lo=0xFF, a_hi=0xFF), text


def load_rom(path: Path, allow_unsupported: bool) -> bytes:
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest().upper()
    if not allow_unsupported and (len(data) != ROM_SIZE or
                                  digest != SUPPORTED_SHA256):
        raise SystemExit(
            f"{path}: unsupported ROM (size {len(data):#x}, sha256 {digest})")
    return data


def build_analyzer(rom: LoRom, args) -> Analyzer:
    bindings = {}
    for item in args.bind or ():
        site, target = item.split("=", 1)
        bindings[parse_address(site)] = parse_address(target)
    return Analyzer(
        rom,
        state_limit=args.state_limit,
        dynamic_bindings=bindings,
        assume_dynamic_preserves=args.assume_dynamic_preserves,
        ram_models={MVN_STUB: mvn_stub_model},
        watched_wram=MVN_OPERANDS)


def _mx_set(values) -> str:
    return ", ".join(sorted({fmt_mx(m, x) for m, x in values})) or "-"


def contract_rows(analyzer: Analyzer, rom: LoRom) -> list[dict]:
    callers_by_target: dict[int, list] = {}
    for summary in analyzer.summaries.values():
        for call in summary.calls + summary.tail_jumps:
            if call.target is not None:
                callers_by_target.setdefault(call.target, []).append(call)

    rows = []
    for (address, m, x), summary in sorted(
            analyzer.summaries.items(),
            key=lambda item: (item[0][0], str(item[0][1]), str(item[0][2]))):
        outcomes = sorted(summary.outcomes, key=lambda o: o.pc)
        rows.append({
            "address": fmt(address),
            "entry": fmt_mx(m, x),
            "sites_in_graph": sorted({fmt(c.site) for c in
                                      callers_by_target.get(address, [])}),
            "rom_callers": [f"{fmt(a)} {k}" for a, k in
                            scan_references(rom, address)],
            "returns": [
                {"pc": fmt(o.pc), "kind": o.kind, "exit": fmt_mx(o.m, o.x),
                 "stack": o.sp, "db": describe_value(o.db),
                 "dp": describe_value(o.dp)} for o in outcomes],
            "stops": [f"{fmt(pc)} {reason}" for pc, reason in summary.stops],
            "dynamic": [f"{fmt(c.site)} {c.kind}: {c.note}" for c in
                        summary.calls + summary.tail_jumps
                        if c.note],
            "caller_db_uses": len(summary.db_uses),
            "first_caller_db_use": min(
                ((fmt(pc), text) for pc, text in summary.db_uses.items()),
                default=None),
            "caller_dp_uses": len(summary.dp_uses),
            "stack_relative": sorted(summary.sr_uses.values()),
            "caller_frame_reads": sorted(summary.frame_reads.values()),
            "mmio": sorted(f"{fmt(pc)} {text}" for pc, text in
                           summary.mmio.items()),
            "mode_changes": len(summary.mode_changes),
            "instructions": len(summary.instructions),
            "truncated": summary.truncated,
        })
    return rows


def markdown(rows: list[dict], root: str, vector_writers: list) -> str:
    out = [f"# Static contract table from {root}", "",
           "Generated by `scripts/ancient_cave_contracts.py`. Static evidence "
           "only; confirm with original-ROM probes.", "",
           "| Routine | Entry | Returns (exit, S, DB, DP) | Caller DB uses | "
           "Caller DP uses | ROM callers | Stops |",
           "|---|---|---|---:|---:|---:|---|"]
    for row in rows:
        returns = "<br>".join(
            f"{r['kind']} {r['pc']} {r['exit']} S{r['stack']:+d} DB {r['db']} "
            f"DP {r['dp']}" if isinstance(r["stack"], int) else
            f"{r['kind']} {r['pc']} {r['exit']} S? DB {r['db']} DP {r['dp']}"
            for r in row["returns"]) or "none"
        stops = "<br>".join(row["stops"]) or "-"
        out.append(
            f"| `{row['address']}` | {row['entry']} | {returns} | "
            f"{row['caller_db_uses']} | {row['caller_dp_uses']} | "
            f"{len(row['rom_callers'])} | {stops} |")
    out += ["", "## MMIO", ""]
    for row in rows:
        for item in row["mmio"]:
            out.append(f"- `{row['address']}`: {item}")
    out += ["", "## Dynamic and modelled transfers", ""]
    for row in rows:
        for item in row["dynamic"]:
            out.append(f"- `{row['address']}`: {item}")
    out += ["", "## Candidate writers of the `$057D-$0580` RAM stub", ""]
    for address, kind in vector_writers:
        out.append(f"- `{fmt(address)}` {kind}")
    out += ["", "## Candidate ROM callers (byte patterns, not decoded)", ""]
    for row in rows:
        if row["rom_callers"]:
            out.append(f"- `{row['address']}`: " +
                       ", ".join(row["rom_callers"]))
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--rom", type=Path, default=Path("lufia2.sfc"))
    parser.add_argument("--root", default="83:9E31")
    parser.add_argument("--entry-mx", default="10",
                        help="entry M and X bits, e.g. 10 for M1/X0")
    parser.add_argument("--bind", action="append",
                        help="SITE_OR_VECTOR=TARGET for a dynamic transfer")
    parser.add_argument("--assume-dynamic-preserves", action="store_true")
    parser.add_argument("--state-limit", type=int, default=200000)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    parser.add_argument("--allow-unsupported-rom", action="store_true",
                        help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    rom = LoRom(load_rom(args.rom, args.allow_unsupported_rom))
    analyzer = build_analyzer(rom, args)
    sys.setrecursionlimit(10000)
    root = parse_address(args.root)
    analyzer.analyze(root, int(args.entry_mx[0]), int(args.entry_mx[1]))
    rows = contract_rows(analyzer, rom)
    writers = scan_ram_writers(rom, 0x057D, 0x0580)
    text = markdown(rows, fmt(root), writers)
    if args.json:
        args.json.write_text(json.dumps(rows, indent=2) + "\n")
    if args.markdown:
        args.markdown.write_text(text)
    if not args.json and not args.markdown:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
