include_guard(GLOBAL)

function(lufia2_target_sound_menu_patch target)
    get_target_property(_sources ${target} SOURCES)
    set(_patched_sources)
    set(_count 0)
    foreach(_input IN LISTS _sources)
        get_filename_component(_name "${_input}" NAME)
        if(NOT _name STREQUAL "bank82_v2.c")
            list(APPEND _patched_sources "${_input}")
            continue()
        endif()
        file(READ "${_input}" _source)
        set(_entry "RecompReturn bank_82_8028_M1X0(CpuState *cpu) {")
        string(FIND "${_source}" "${_entry}" _start)
        if(_start EQUAL -1)
            message(FATAL_ERROR "Sound menu dispatcher entry changed")
        endif()
        string(SUBSTRING "${_source}" ${_start} -1 _tail)
        string(FIND "${_tail}" "\nRecompReturn " _end)
        if(_end EQUAL -1)
            string(LENGTH "${_tail}" _end)
        endif()
        string(SUBSTRING "${_tail}" 0 ${_end} _body)
        set(_store [=[
    uint16 _v9 = cpu_read_a16(cpu);
    cpu_write16(cpu, 0x00, (uint16)(cpu->D + 0x0060), _v9);
]=])
        string(REPLACE "${_store}" "" _removed "${_body}")
        string(LENGTH "${_body}" _before)
        string(LENGTH "${_removed}" _after)
        string(LENGTH "${_store}" _length)
        math(EXPR _matches "${_before} - ${_after}")
        if(NOT _matches EQUAL _length)
            message(FATAL_ERROR "Sound menu target store changed")
        endif()
        string(REPLACE "${_store}"
            "    Lufia2SoundMenuCorrectTarget(cpu, ((uint32_t)cpu->PB << 16) | 0x803du);\n${_store}"
            _patched_body "${_body}")
        string(SUBSTRING "${_source}" 0 ${_start} _prefix)
        math(EXPR _suffix_start "${_start} + ${_end}")
        string(SUBSTRING "${_source}" ${_suffix_start} -1 _suffix)
        set(_directory "${CMAKE_BINARY_DIR}/generated/lufia2-sound-menu")
        set(_output "${_directory}/${_name}")
        file(MAKE_DIRECTORY "${_directory}")
        file(WRITE "${_output}"
            "#include \"patches/lufia2_sound_menu.h\"\n${_prefix}${_patched_body}${_suffix}")
        get_filename_component(_original_directory "${_input}" DIRECTORY)
        get_source_file_property(_includes "${_input}" INCLUDE_DIRECTORIES)
        if(_includes STREQUAL "NOTFOUND")
            set(_includes "")
        endif()
        set_source_files_properties("${_output}" PROPERTIES
            INCLUDE_DIRECTORIES "${_original_directory};${_includes}")
        foreach(_property COMPILE_OPTIONS COMPILE_DEFINITIONS)
            get_source_file_property(_value "${_input}" ${_property})
            if(NOT _value STREQUAL "NOTFOUND")
                set_source_files_properties("${_output}" PROPERTIES ${_property} "${_value}")
            endif()
        endforeach()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_input}")
        list(APPEND _patched_sources "${_output}")
        math(EXPR _count "${_count} + 1")
    endforeach()
    if(NOT _count EQUAL 1)
        message(FATAL_ERROR "Expected one compiled sound menu dispatcher")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${_patched_sources}")
endfunction()
