include_guard(GLOBAL)

# Build identity for profile captures, refreshed on every build.
set(_LUFIA2_BUILD_IDENTITY_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

if(CMAKE_SCRIPT_MODE_FILE)
    function(lufia2_identity_git_head dir out_var)
        execute_process(
            COMMAND git -C "${dir}" rev-parse HEAD
            OUTPUT_VARIABLE _head
            OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE _result
            ERROR_QUIET)
        if(NOT _result EQUAL 0 OR NOT _head)
            set(${out_var} "unknown" PARENT_SCOPE)
            return()
        endif()
        execute_process(
            COMMAND git -C "${dir}" status --porcelain --untracked-files=no
            OUTPUT_VARIABLE _changes
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET)
        if(_changes)
            string(APPEND _head "-dirty")
        endif()
        set(${out_var} "${_head}" PARENT_SCOPE)
    endfunction()

    lufia2_identity_git_head("${SOURCE_DIR}" _superproject)
    lufia2_identity_git_head("${DECOMP_DIR}" _decomp)
    set(_manifest "unknown")
    if(EXISTS "${MANIFEST}")
        file(SHA256 "${MANIFEST}" _manifest)
    endif()
    set(_text "/* Generated by cmake/Lufia2BuildIdentity.cmake. */\n")
    string(APPEND _text "#define LUFIA2_BUILD_SUPERPROJECT \"${_superproject}\"\n")
    string(APPEND _text "#define LUFIA2_BUILD_DECOMP \"${_decomp}\"\n")
    string(APPEND _text "#define LUFIA2_BUILD_SNESRECOMP \"${SNESRECOMP}\"\n")
    string(APPEND _text "#define LUFIA2_BUILD_CONFIG \"${CONFIG}\"\n")
    string(APPEND _text "#define LUFIA2_BUILD_MANIFEST_SHA256 \"${_manifest}\"\n")
    set(_old "")
    if(EXISTS "${OUTPUT}")
        file(READ "${OUTPUT}" _old)
    endif()
    if(NOT _old STREQUAL _text)
        file(WRITE "${OUTPUT}" "${_text}")
    endif()
    return()
endif()

function(lufia2_add_build_identity target)
    set(_dir "${CMAKE_BINARY_DIR}/generated/build-identity")
    set(_header "${_dir}/lufia2_build_identity_values.h")
    set(_decomp "${LUFIA2_DECOMP_ROOT}")
    if(NOT _decomp)
        set(_decomp "${CMAKE_SOURCE_DIR}/lib/lufia2-decomp")
    endif()
    get_filename_component(_snesrecomp "${SNESRECOMP_ROOT}" NAME)
    file(MAKE_DIRECTORY "${_dir}")
    add_custom_target(Lufia2BuildIdentity
        COMMAND "${CMAKE_COMMAND}"
            "-DSOURCE_DIR=${CMAKE_SOURCE_DIR}"
            "-DDECOMP_DIR=${_decomp}"
            "-DMANIFEST=${CMAKE_BINARY_DIR}/lufia2-gen/program_manifest.json"
            "-DSNESRECOMP=${_snesrecomp}"
            "-DCONFIG=$<CONFIG>"
            "-DOUTPUT=${_header}"
            -P "${_LUFIA2_BUILD_IDENTITY_SCRIPT}"
        BYPRODUCTS "${_header}"
        VERBATIM)
    add_dependencies(${target} Lufia2BuildIdentity)
    target_sources(${target} PRIVATE
        "${CMAKE_SOURCE_DIR}/src/lufia2_build_identity.c")
    target_include_directories(${target} PRIVATE "${_dir}")
endfunction()
